apiVersion: v1
data:
  autounattend.xml: "<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<unattend xsi:schemaLocation=\"urn:schemas-microsoft-com:unattend\"
    xmlns=\"urn:schemas-microsoft-com:unattend\" xmlns:wcm=\"http://schemas.microsoft.com/WMIConfig/2002/State\"
    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n    <settings pass=\"windowsPE\">\r\n
    \       <component name=\"Microsoft-Windows-Setup\" processorArchitecture=\"amd64\"
    publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\" versionScope=\"nonSxS\">\r\n
    \           <DiskConfiguration>\r\n                <Disk wcm:action=\"add\">\r\n
    \                   <DiskID>0</DiskID>\r\n                    <WillWipeDisk>true</WillWipeDisk>\r\n
    \                   <CreatePartitions>\r\n                        <!-- Windows
    RE Tools partition -->\r\n                        <CreatePartition wcm:action=\"add\">\r\n
    \                           <Order>1</Order>\r\n                            <Type>Primary</Type>\r\n
    \                           <Size>500</Size>\r\n                        </CreatePartition>\r\n
    \                       <!-- System partition (ESP) -->\r\n                        <CreatePartition
    wcm:action=\"add\">\r\n                            <Order>2</Order>\r\n                            <Type>EFI</Type>\r\n
    \                           <Size>1024</Size>\r\n                        </CreatePartition>\r\n
    \                       <!-- Microsoft reserved partition (MSR) -->\r\n                        <CreatePartition
    wcm:action=\"add\">\r\n                            <Order>3</Order>\r\n                            <Type>MSR</Type>\r\n
    \                           <Size>128</Size>\r\n                        </CreatePartition>\r\n
    \                       <!-- Windows partition -->\r\n                        <CreatePartition
    wcm:action=\"add\">\r\n                            <Order>4</Order>\r\n                            <Type>Primary</Type>\r\n
    \                           <Extend>true</Extend>\r\n                        </CreatePartition>\r\n
    \                   </CreatePartitions>\r\n                    <ModifyPartitions>\r\n
    \                       <!-- Windows RE Tools partition -->\r\n                        <ModifyPartition
    wcm:action=\"add\">\r\n                            <Order>1</Order>\r\n                            <PartitionID>1</PartitionID>\r\n
    \                           <Label>WINRE</Label>\r\n                            <Format>NTFS</Format>\r\n
    \                           <TypeID>DE94BBA4-06D1-4D40-A16A-BFD50179D6AC</TypeID>\r\n
    \                       </ModifyPartition>\r\n                        <!-- System
    partition (ESP) -->\r\n                        <ModifyPartition wcm:action=\"add\">\r\n
    \                           <Order>2</Order>\r\n                            <PartitionID>2</PartitionID>\r\n
    \                           <Label>System</Label>\r\n                            <Format>FAT32</Format>\r\n
    \                       </ModifyPartition>\r\n                        <!-- MSR
    partition does not need to be modified -->\r\n                        <ModifyPartition
    wcm:action=\"add\">\r\n                            <Order>3</Order>\r\n                            <PartitionID>3</PartitionID>\r\n
    \                       </ModifyPartition>\r\n                        <!-- Windows
    partition -->\r\n                        <ModifyPartition wcm:action=\"add\">\r\n
    \                           <Order>4</Order>\r\n                            <PartitionID>4</PartitionID>\r\n
    \                           <Label>OS</Label>\r\n                            <Letter>C</Letter>\r\n
    \                           <Format>NTFS</Format>\r\n                        </ModifyPartition>\r\n
    \                   </ModifyPartitions>\r\n                </Disk>\r\n            </DiskConfiguration>\r\n
    \           <ImageInstall>\r\n                <OSImage>\r\n                    <InstallFrom>\r\n
    \                       <MetaData wcm:action=\"add\">\r\n                            <Key>/IMAGE/NAME</Key>\r\n
    \                           <Value>Windows Server 2019 SERVERSTANDARD</Value>\r\n
    \                       </MetaData>\r\n                    </InstallFrom>\r\n
    \                   <InstallTo>\r\n                        <DiskID>0</DiskID>\r\n
    \                       <PartitionID>4</PartitionID>\r\n                    </InstallTo>\r\n
    \               </OSImage>\r\n            </ImageInstall>\r\n            <UserData>\r\n
    \               <AcceptEula>true</AcceptEula>\r\n                <FullName>Administrator</FullName>\r\n
    \               <Organization>My Organization</Organization>\r\n            </UserData>\r\n
    \           <EnableFirewall>false</EnableFirewall>\r\n        </component>\r\n
    \       <component name=\"Microsoft-Windows-International-Core-WinPE\" processorArchitecture=\"amd64\"
    publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\" versionScope=\"nonSxS\">\r\n
    \           <SetupUILanguage>\r\n                <UILanguage>en-US</UILanguage>\r\n
    \           </SetupUILanguage>\r\n            <InputLocale>en-US</InputLocale>\r\n
    \           <SystemLocale>en-US</SystemLocale>\r\n            <UILanguage>en-US</UILanguage>\r\n
    \           <UserLocale>en-US</UserLocale>\r\n        </component>\r\n        <component
    name=\"Microsoft-Windows-PnpCustomizationsWinPE\" processorArchitecture=\"amd64\"
    publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\" versionScope=\"nonSxS\">\r\n
    \           <DriverPaths>\r\n                <PathAndCredentials wcm:keyValue=\"4b29ba63\"
    wcm:action=\"add\">\r\n                    <Path>E:\\amd64\\2k19</Path>\r\n                </PathAndCredentials>\r\n
    \               <PathAndCredentials wcm:keyValue=\"25fe51ea\" wcm:action=\"add\">\r\n
    \                   <Path>E:\\NetKVM\\2k19\\amd64</Path>\r\n                </PathAndCredentials>\r\n
    \           </DriverPaths>\r\n        </component>\r\n    </settings>\r\n    <settings
    pass=\"offlineServicing\">\r\n        <component name=\"Microsoft-Windows-LUA-Settings\"
    processorArchitecture=\"amd64\" publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\"
    versionScope=\"nonSxS\">\r\n            <EnableLUA>false</EnableLUA>\r\n        </component>\r\n
    \   </settings>\r\n    <settings pass=\"specialize\">\r\n        <component name=\"Microsoft-Windows-Shell-Setup\"
    processorArchitecture=\"amd64\" publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\"
    versionScope=\"nonSxS\">\r\n            <AutoLogon>\r\n                <Password>\r\n
    \                   <Value>R3dh4t1!</Value>\r\n                    <PlainText>true</PlainText>\r\n
    \               </Password>\r\n                <Enabled>true</Enabled>\r\n                <LogonCount>999</LogonCount>\r\n
    \               <Username>Administrator</Username>\r\n            </AutoLogon>\r\n
    \           <OOBE>\r\n                <HideEULAPage>true</HideEULAPage>\r\n                <HideLocalAccountScreen>true</HideLocalAccountScreen>\r\n
    \               <HideOnlineAccountScreens>true</HideOnlineAccountScreens>\r\n
    \               <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>\r\n                <NetworkLocation>Work</NetworkLocation>\r\n
    \               <ProtectYourPC>3</ProtectYourPC>\r\n                <SkipMachineOOBE>true</SkipMachineOOBE>\r\n
    \           </OOBE>\r\n            <UserAccounts>\r\n                <LocalAccounts>\r\n
    \                   <LocalAccount wcm:action=\"add\">\r\n                        <Description>Local
    Administrator Account</Description>\r\n                        <DisplayName>Administrator</DisplayName>\r\n
    \                       <Group>Administrators</Group>\r\n                        <Name>Administrator</Name>\r\n
    \                   </LocalAccount>\r\n                </LocalAccounts>\r\n            </UserAccounts>\r\n
    \           <TimeZone>Mountain Standard Time</TimeZone>\r\n        </component>\r\n
    \   </settings>\r\n    <settings pass=\"oobeSystem\">\r\n        <component name=\"Microsoft-Windows-International-Core\"
    processorArchitecture=\"amd64\" publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\"
    versionScope=\"nonSxS\">\r\n            <InputLocale>en-US</InputLocale>\r\n            <SystemLocale>en-US</SystemLocale>\r\n
    \           <UILanguage>en-US</UILanguage>\r\n            <UserLocale>en-US</UserLocale>\r\n
    \       </component>\r\n        <component name=\"Microsoft-Windows-Shell-Setup\"
    processorArchitecture=\"amd64\" publicKeyToken=\"31bf3856ad364e35\" language=\"neutral\"
    versionScope=\"nonSxS\">\r\n            <AutoLogon>\r\n                <Password>\r\n
    \                   <Value>R3dh4t1!</Value>\r\n                    <PlainText>true</PlainText>\r\n
    \               </Password>\r\n                <Enabled>true</Enabled>\r\n                <LogonCount>999</LogonCount>\r\n
    \               <Username>Administrator</Username>\r\n            </AutoLogon>\r\n
    \           <FirstLogonCommands>\r\n                <SynchronousCommand wcm:action=\"add\">\r\n
    \                   <CommandLine>powershell -noexit f:\\post-install.ps1\r\n          </CommandLine>\r\n
    \                   <RequiresUserInput>false</RequiresUserInput>\r\n                    <Order>1</Order>\r\n
    \                   <Description>Post Installation Script</Description>\r\n                </SynchronousCommand>\r\n
    \           </FirstLogonCommands>\r\n            <OOBE>\r\n                <HideEULAPage>true</HideEULAPage>\r\n
    \               <HideLocalAccountScreen>true</HideLocalAccountScreen>\r\n                <HideOnlineAccountScreens>true</HideOnlineAccountScreens>\r\n
    \               <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>\r\n                <NetworkLocation>Work</NetworkLocation>\r\n
    \               <ProtectYourPC>3</ProtectYourPC>\r\n                <SkipMachineOOBE>true</SkipMachineOOBE>\r\n
    \           </OOBE>\r\n            <UserAccounts>\r\n                <LocalAccounts>\r\n
    \                   <LocalAccount wcm:action=\"add\">\r\n                        <Description>Local
    Administrator Account</Description>\r\n                        <DisplayName>Administrator</DisplayName>\r\n
    \                       <Group>Administrators</Group>\r\n                        <Name>Administrator</Name>\r\n
    \                   </LocalAccount>\r\n                </LocalAccounts>\r\n            </UserAccounts>\r\n
    \           <TimeZone>Mountain Standard Time</TimeZone>\r\n        </component>\r\n
    \   </settings>\r\n    <cpi:offlineImage cpi:source=\"\" xmlns:cpi=\"urn:schemas-microsoft-com:cpi\"
    />\r\n</unattend>\r\n"
  clone-boot-source-old.yaml: |
    apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: win2k19-old
      namespace: openshift-virtualization-os-images
      annotations:
        cdi.kubevirt.io/storage.bind.immediate.requested: "true"
        kubevirt.ui/provider: Microsoft
    spec:
      source:
        pvc:
          namespace: openshift-virtualization-os-images
          name: win2k19-old
      pvc:
        accessModes:
        - ReadWriteMany
        volumeMode: Block
        resources:
          requests:
            storage: 60Gi
  clone-boot-source.yaml: |
    apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: win2k19
      namespace: openshift-virtualization-os-images
      annotations:
        cdi.kubevirt.io/storage.bind.immediate.requested: "true"
        kubevirt.ui/provider: Microsoft
    spec:
      source:
        pvc:
          namespace: kubevirt-gitops
          name: windows-install-rootdisk
      pvc:
        accessModes:
        - ReadWriteMany
        volumeMode: Block
        resources:
          requests:
            storage: 60Gi
  install.sh: |
    #!/bin/sh

    echo "Starting install script"
    cd /scripts

    # https://hyperconverged-cluster-cli-download-openshift-cnv.apps.ocs.openshift.works/amd64/linux/virtctl.tar.gz
    wget http://hyperconverged-cluster-cli-download.openshift-cnv.svc.cluster.local:8080/amd64/linux/virtctl.tar.gz
    tar -xzvf virtctl.tar.gz

    oc apply -f windows-install-vm.yaml
    echo "Applied VM"
    sleep 5

    virtctl start windows-install
    echo "Started VM, waiting for VM to start"
    sleep 5

    vm_ready=$(oc get vm windows-install -o jsonpath='{.status.ready}')
    while [ "$vm_ready" != "true" ]
    do
        sleep 10
        vm_ready=$(oc get vm windows-install -o jsonpath='{.status.ready}')
    done

    echo "VM is started. Waiting for VMI to finish successfully."
    vmi_phase=$(oc get vmi windows-install -o jsonpath='{.status.phase}')
    while [ "$vmi_phase" != "Succeeded" ]
    do
        sleep 30
        vmi_phase=$(oc get vmi windows-install -o jsonpath='{.status.phase}')
        if [ "$vmi_phase" == "" ]; then
            vmi_phase="Succeeded"
        fi
    done

    echo "VM has finished installing"
    oc apply -f clone-boot-source.yaml
    echo "Applied DataVolume to clone boot source image"

    sleep 5
    dv_phase=$(oc -n openshift-virtualization-os-images get dv win2k19 -o jsonpath='{.status.phase}')
    while [ "$dv_phase" != "Succeeded" ]
    do
        sleep 10
        dv_phase=$(oc -n openshift-virtualization-os-images get dv win2k19 -o jsonpath='{.status.phase}')
        echo $dv_phase
    done

    echo "Cleaning up"
    oc delete -f windows-install-vm.yaml

    my_app_name=$(oc get cm windows-install-scripts -o jsonpath='{.metadata.labels.app\.kubernetes\.io/instance}')

    echo "Finished"
  post-install.ps1: |
    # Create Workdir
    $BasePath = "C:\Windows\Temp\Install"
    New-item $BasePath -itemtype directory

    # Enable RDP
    Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
    Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    # Add RedHat to Trusted Publisher
    $CertName = "balloon.cer"
    $ExportCert = Join-Path $BasePath -ChildPath $CertName

    $Cert = (Get-AuthenticodeSignature "D:\Balloon\2k19\amd64\balloon.sys").SignerCertificate
    $ExportType = [System.Security.Cryptography.X509Certificates.X509ContentType]::Cert

    [System.IO.File]::WriteAllBytes($ExportCert, $Cert.Export($ExportType))
    Import-Certificate -FilePath $ExportCert -CertStoreLocation Cert:\LocalMachine\TrustedPublisher

    # install Guest Agent
    msiexec /i e:\virtio-win-gt-x64.msi /qn /passive

    # install Qemu Tools (Drivers)
    msiexec /i e:\guest-agent\qemu-ga-x86_64.msi /qn /passive

    # Fix Guest Agent
    Start-Process  E:\vioserial\2k19\amd64\vioser.inf -Verb install

    # Get Cloud-init
    Set-ExecutionPolicy Unrestricted
    $Cloudinit = "CloudbaseInitSetup_Stable_x64.msi"
    $CloutinitLocaion =  Join-Path -Path "C:\windows\temp\" -ChildPath $Cloudinit
    invoke-webrequest https://www.cloudbase.it/downloads/$Cloudinit -o $CloutinitLocaion

    cmd /C start /wait msiexec /i $CloutinitLocaion /qn

    # Cleanup
    Remove-item $BasePath -Recurse

    # Remove AutoLogin
    # reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v AutoAdminLogon /t REG_SZ /d 0 /f

    # Run Sysprep and Shutdown
    #
    #Push-Location "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\conf\"
    #C:\Windows\System32\Sysprep\sysprep.exe /generalize /oobe /shutdown /unattend:Unattend.xml

    cmd /C 'cd "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\conf\" && C:\Windows\System32\Sysprep\sysprep.exe /generalize /oobe /shutdown /unattend:Unattend.xml'

    # Perform windows updates
    Install-Module PSWindowsUpdate -Force -AcceptLicense -Confirm
    Get-WindowsUpdate
    Install-WindowsUpdate -AcceptAll -AutoReboot

    Start-Sleep -Duration (New-TimeSpan -Seconds 600); Stop-Computer
  windows-install-vm.yaml: "apiVersion: kubevirt.io/v1\nkind: VirtualMachine\nmetadata:\n
    \ annotations:\n    name.os.template.kubevirt.io/win2k19: Microsoft Windows Server
    2019\n    description: windows-install\n  labels:\n    app: windows-install\n
    \ name: windows-install\nspec:\n  runStrategy: Manual\n  template:\n    metadata:\n
    \     annotations:\n        vm.kubevirt.io/os: windows2k19\n        vm.kubevirt.io/workload:
    server\n      labels:\n        kubevirt.io/domain: windows-install\n        vm.kubevirt.io/name:
    windows-install\n        workload.template.kubevirt.io/server: 'true'\n    spec:\n
    \     architecture: amd64\n      domain:\n        clock:\n          timer:\n            hpet:\n
    \             present: false\n            hyperv: {}\n            pit:\n              tickPolicy:
    delay\n            rtc:\n              tickPolicy: catchup\n          utc: {}\n
    \       cpu:\n          cores: 1\n          sockets: 2\n          threads: 1\n
    \       devices:\n          disks:\n          - name: windows-install-rootdisk\n
    \           disk:\n              bus: sata\n          - name: win2k19-install-iso\n
    \           bootOrder: 1\n            cdrom:\n              bus: sata\n          -
    name: windows-guest-tools\n            cdrom:\n              bus: sata\n          -
    name: windows-install-scripts\n            cdrom:\n              bus: sata\n          inputs:\n
    \           - bus: usb\n              name: tablet\n              type: tablet\n
    \         interfaces:\n          - name: default\n            model: virtio\n
    \           masquerade: {}\n          networkInterfaceMultiqueue: true\n          rng:
    {}\n          logSerialConsole: false\n        features:\n          acpi: {}\n
    \         apic: {}\n          hyperv:\n            reenlightenment: {}\n            ipi:
    {}\n            synic: {}\n            synictimer:\n              direct: {}\n
    \           spinlocks:\n              spinlocks: 8191\n            reset: {}\n
    \           relaxed: {}\n            vpindex: {}\n            runtime: {}\n            tlbflush:
    {}\n            frequencies: {}\n            vapic: {}\n          smm: {}\n        firmware:\n
    \         bootloader:\n            efi:\n              secureBoot: true\n        machine:\n
    \         type: pc-q35-rhel9.4.0\n        memory:\n          guest: 4Gi\n      evictionStrategy:
    LiveMigrate\n      hostname: windows-install\n      networks:\n      - name: default\n
    \       pod: {}\n      terminationGracePeriodSeconds: 180\n      volumes:\n      -
    name: windows-install-rootdisk \n        dataVolume:\n          name: windows-install-rootdisk\n
    \     - name: win2k19-install-iso\n        persistentVolumeClaim:\n          claimName:
    win2k19-install-iso\n      - name: windows-guest-tools\n        containerDisk:\n
    \         image: registry.redhat.io/container-native-virtualization/virtio-win-rhel9:v4.17\n
    \     - name: windows-install-scripts\n        configMap:\n          name: windows-install-scripts\n
    \ dataVolumeTemplates:\n  - metadata:\n      name: windows-install-rootdisk\n
    \   spec:\n      pvc:\n        accessModes:\n        - ReadWriteMany\n        volumeMode:
    Block\n        resources:\n          requests:\n            storage: 60Gi\n      source:\n
    \       blank: {}\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: windows-install-scripts
  namespace: kubevirt-gitops
