apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: win2k19-old
  namespace: openshift-virtualization-os-images
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    kubevirt.ui/provider: Microsoft
spec:
  source:
    pvc:
      namespace: openshift-virtualization-os-images
      name: win2k19-old
  pvc:
    accessModes:
    - ReadWriteMany
    volumeMode: Block
    resources:
      requests:
        storage: 60Gi
