apiVersion: v1
kind: Service
metadata:
  name: vm-pool-win2k19-ssh
spec:
  type: ClusterIP
  selector:
    kubevirt.io/vmpool: vm-pool-win2k19
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 22