apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    name.os.template.kubevirt.io/win2k19: Microsoft Windows Server 2019
    description: windows-install
  labels:
    app: windows-install
  name: windows-install
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        vm.kubevirt.io/os: windows2k19
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: windows-install
        vm.kubevirt.io/name: windows-install
        workload.template.kubevirt.io/server: 'true'
    spec:
      architecture: amd64
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
          - name: windows-install-rootdisk
            disk:
              bus: sata
          - name: win2k19-install-iso
            bootOrder: 1
            cdrom:
              bus: sata
          - name: windows-guest-tools
            cdrom:
              bus: sata
          - name: windows-install-scripts
            cdrom:
              bus: sata
          inputs:
            - bus: usb
              name: tablet
              type: tablet
          interfaces:
          - name: default
            model: virtio
            masquerade: {}
          networkInterfaceMultiqueue: true
          rng: {}
          logSerialConsole: false
        features:
          acpi: {}
          apic: {}
          hyperv:
            reenlightenment: {}
            ipi: {}
            synic: {}
            synictimer:
              direct: {}
            spinlocks:
              spinlocks: 8191
            reset: {}
            relaxed: {}
            vpindex: {}
            runtime: {}
            tlbflush: {}
            frequencies: {}
            vapic: {}
          smm: {}
        firmware:
          bootloader:
            efi:
              secureBoot: true
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
      evictionStrategy: LiveMigrate
      hostname: windows-install
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - name: windows-install-rootdisk 
        dataVolume:
          name: windows-install-rootdisk
      - name: win2k19-install-iso
        persistentVolumeClaim:
          claimName: win2k19-install-iso
      - name: windows-guest-tools
        containerDisk:
          image: registry.redhat.io/container-native-virtualization/virtio-win-rhel9:v4.17
      - name: windows-install-scripts
        configMap:
          name: windows-install-scripts
  dataVolumeTemplates:
  - metadata:
      name: windows-install-rootdisk
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        volumeMode: Block
        resources:
          requests:
            storage: 60Gi
      source:
        blank: {}
