apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vms
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: kubevirt-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
<<<<<<< HEAD
    path: vms
    repoURL: https://github.com/therevoman/kubevirt-gitops.git
=======
    path: vms/overlays/kubernetes
    repoURL: https://github.com/cwilkers/kubevirt-gitops.git
>>>>>>> 5c2b896 (retooled to make app of apps work)
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
