apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windows-install
spec:
  destination:
    namespace: ""
    server: https://kubernetes.default.svc
  project: default
  source:
    path: win2k19
<<<<<<< HEAD
    repoURL: https://github.com/therevoman/kubevirt-gitops.git
=======
    repoURL: https://github.com/cwilkers/kubevirt-gitops.git
>>>>>>> 5c2b896 (retooled to make app of apps work)
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
