apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windows-install
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: ""
    server: https://kubernetes.default.svc
  project: default
  source:
    path: win2k19
    repoURL: https://github.com/therevoman/kubevirt-gitops.git
    targetRevision: ocs
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
