apiVersion: batch/v1
kind: Job
metadata:
  name: windows-2k22-install
  namespace: kubevirt-gitops
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: windows-2k22-install
      restartPolicy: Never
      containers:
      - name: ose-cli
        image: registry.redhat.io/openshift4/ose-cli-rhel9:latest
        volumeMounts:
        - name: windows-2k22-install-scripts
          mountPath: /scripts
        command: ["/bin/sh"]
        args: ["/scripts/install.sh"]
      volumes:
      - name: windows-2k22-install-scripts
        configMap:
          name: windows-2k22-install-scripts

